version: "2.1"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: max
    #   MONGO_INITDB_ROOT_PASSWORD: secret
      # - MONGO_INITDB_ROOT_USERNAME=max
  backend:
    build: ./server
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args:
    #     some-arg: 1
    ports:
      - '5000:5000'
    volumes: 
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    env_file: 
      - ./server/.env
    depends_on:
      - mongodb
  frontend:
    build: ./client
    ports: 
      - '3000:3000'
    volumes: 
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data:
  logs:
