
POST http://localhost:3000/instructors
Content-Type: application/json

{
    "name": "Yosi Cohen",
    "gender": "Male",
    "birthdate": "1995-07-16T02:13:33.959Z",
    "seniority": 5
}

###

POST http://localhost:3000/instructors
Content-Type: application/json

{
    "name": "Elad Levi",
    "gender": "Male",
    "birthdate": "1997-10-19T02:13:33.959Z",
    "seniority": 2
}

###
POST http://localhost:3000/instructors
Content-Type: application/json

{
    "name": "Sharon Yam",
    "gender": "Female",
    "birthdate": "2000-09-16T02:13:33.959Z",
    "seniority": 1
}


###

POST http://localhost:3000/students
Content-Type: application/json

{
    "name": "Alon Shlomi",
    "gender": "Male",
    "birthdate": "1995-07-16T02:13:33.959Z"
}

###

POST http://localhost:3000/students
Content-Type: application/json

{
    "name": "coral Cohen",
    "gender": "femalw",
    "birthdate": "1998-02-10T02:13:33.959Z"
}

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "aa@gmail.com",
    "password": "123",
    "type": "admin",
    "object": ""
}

