GET http://localhost:5000/students


###

POST http://localhost:5000/students
Content-Type: application/json

{
    "name": "Alon Shlomi",
    "gender": "Male",
    "birthdate": "1995-07-16T02:13:33.959Z"
}

###

GET http://localhost:3000/students/646a113e09eeed56b4e53f76


###
DELETE http://localhost:3000/students/646a113e09eeed56b4e53f76



###
PATCH http://localhost:3000/instructors/6469f61fbe35dd2dd7577672
Content-Type: application/json

{
    "name": "Alon Shlomi"

}